### ISSUE TITLE
Support passing -exclude flag

### ISSUE THREAD

**Issue by bluekeyes** [palantir/godel-okgo-asset-errcheck#15]
According to the [errcheck README](https://github.com/kisielk/errcheck), the `-ignore` flag is deprecated and replaced by the `-exclude` flag. I prefer to use the `-exclude` flag to ignore functions over other options because it matches on exact Go types, rather than on regular expressions.

I think the ideal implementation would allow users to specify the list of excludes in `check-plugin.yml` and Godel would automatically create the necessary file on disk when invoking `errcheck`.

**Comment by nmiyake** [comment]
Thanks! gödel 2.8.0 has been released, and it contains the new version of the asset that has this fix.
